name: model-wine-quality
on: [push]
jobs:
  run:
    runs-on: [ubuntu-latest]
    # optionally use a convenient Ubuntu LTS + DVC + CML image
    container: docker://dvcorg/cml-py3:latest
    steps:
      - uses: actions/checkout@v3
      # - uses: iterative/setup-tools@v1
      - name: cml_run
        env:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
        run: |
        
          # Your ML workflow goes here
          pip install -r requirements.txt
          python train.py
          
          echo "## Model Metrics" > report.m
          cat metrics.txt >> report.md
          
          echo "## Data vix" >> report.md
          cml-publish feature_importance.png --md >> report.md
          cml-publish residuals.png --md >> report.md
          cml-send-comment report.md
